//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocket.Launcher.R {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="R.IRocketService")]
    public interface IRocketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRocketService/HelloWorld", ReplyAction="http://tempuri.org/IRocketService/HelloWorldResponse")]
        void HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRocketService/HelloWorld", ReplyAction="http://tempuri.org/IRocketService/HelloWorldResponse")]
        System.Threading.Tasks.Task HelloWorldAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRocketServiceChannel : Rocket.Launcher.R.IRocketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RocketServiceClient : System.ServiceModel.ClientBase<Rocket.Launcher.R.IRocketService>, Rocket.Launcher.R.IRocketService {
        
        public RocketServiceClient() {
        }
        
        public RocketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RocketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RocketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RocketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void HelloWorld() {
            base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
    }
}
