
// This file has been generated by the GUI designer. Do not modify.
namespace Rocket.Launcher
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button button2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Rocket.Launcher.MainWindow
			this.Name = "Rocket.Launcher.MainWindow";
			this.Title = "MainWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Rocket.Launcher.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = "GtkButton";
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w1.X = 127;
			w1.Y = 85;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
